

greetings = [
    "what's up?",
    "how can I help you?",
    "what do you need?",
    "yeah?",
    "i am ready!",
    "what do you want?",
    "yes",
    "how can I help?",
    "always wanting something",
]


state_codes = {'nevada': 'NV',
               'california': 'CA',
               'texas': 'TX',
               'florida': 'FL',
               'washington': 'WA',
               'alabama': 'AL',
               'alaska': 'AK',
               'arizona': 'AZ',
               'arkansas': 'AR',
               'colorado': 'CO',
               'connecticut': 'CT',
               'delaware': 'DE',
               'district of columbia': 'DC',
               'georgia': 'GA',
               'hawaii': 'HI',
               'idaho': 'ID',
               'illinois': 'IL',
               'indiana': 'IN',
               'iowa': 'IA',
               'kansas': 'KS',
               'kentucky': 'KY',
               'louisiana': 'LA',
               'maine': 'ME',
               'maryland': 'MD',
               'massachusetts': 'MA',
               'michigan': 'MI',
               'minnesota': 'MN',
               'mississippi': 'MS',
               'missouri': 'MO',
               'montana': 'MT',
               'utah': 'UT',
               'vermont': 'VT',
               'virginia': 'VA',
               'virgin islands': 'VI',
               'west virginia': 'WV',
               'wisconsin': 'WI',
               'wyoming': 'WY',
               'tennessee': 'TN',
               'south dakota': 'SD',
               'south carolina': 'SC',
               'rhode island': 'RI',
               'puerto rico': 'RP',
               'pennsylvania': 'PA',
               'oregon': 'OR',
               'oklahoma': 'OK',
               'ohio': 'OH',
               'north dakota': 'ND',
               'north carolina': 'NC',
               'new york': 'NY',
               'new mexico': 'NM',
               'new jersey': 'NJ',
               'new hampshire': 'NH',
               'nebraska': 'NE'}



# prolbem with new york is because most states are one word and the code above returns 2 or 3 indexes